### ISSUE TITLE
Updating categories

### ISSUE THREAD

**Issue by spablex** [dim00z/gshoppingflux#18]
There is a problem when there is a large amount of categories, when updating the taxonomy that Google requires. It exports over and over again when you save the configuration

**Comment by Casper-O** [comment]
i'm Looking into it

**Comment by Casper-O** [comment]
Solved

**Comment by dim00z** [comment]
Tested on PS 1.5.6.2 and whatever the "Automatic export on saves?" selected option, products are exported anyway... I'll have a look at it asap, if it can be corrected on these PS 1.5 versions.

**Comment by Casper-O** [comment]
That sounds interesting. It's a simple check if it's true/false, and depending on that it will go to generateFiles or not.

I'll setup a local 1.6.0.9 and 1.5.6.2 prestashop later this week I can test on, to check compatibly for future release. My setup have been playing Easter tricks on me, so I might have to make a clean setup
