### ISSUE TITLE
attribute_id number missing

### ISSUE THREAD

**Issue by Niemand101** [dim00z/gshoppingflux#20]
with the update to 1.6.1x the url of combination attributes isn't working anymore. the attribute_id number isn't in the generated url

prestashop demo:
http://fo.demo.prestashop.com/en/blouses/2-9-blouse.html#/2-size-m/11-color-black

flux url:
http://fo.demo.prestashop.com/en/blouses/2-9-blouse.html#/size-m/color-black

with this url it reverts back to default product combination

**Comment by Casper-O** [comment]
Did this work prior to 1.6.1.x ?

Sorry but I have not testes this module myself on other than 1.6.1.x release?

**Comment by Niemand101** [comment]
Casper what version are you using? I see prestashop 1.6.0.14 already changed the url generation way.

http://client.basv.nl/presta16014/index.php?id_product=1&controller=product#/1-size-s/13-color-orange

the attribute id is now in the url

**Comment by Casper-O** [comment]
I'm using 1.6.1.x - so I need to know a version when this changed to figure out if I need to take care of something special depending on version number

**Comment by Casper-O** [comment]
I think you can solve this if you change line 2192 in gshoppingflux.php from:

`        $product_link = $this->context->link->getProductLink((int) ($product['id_product']), $product['link_rewrite'], $cat_link_rew, $product['ean13'], (int) ($product['id_lang']), $id_shop, $combination, true);
`
To this:
`        $product_link = $this->context->link->getProductLink((int) ($product['id_product']), $product['link_rewrite'], $cat_link_rew, $product['ean13'], (int) ($product['id_lang']), $id_shop, $combination, true, false, true);
`

But again, i don't know, how this will affect previous versions

**Comment by Casper-O** [comment]
@ Niemand101 possible I could ask you to check #21 and see if it also solves for you? maybe if you have an older Prestashop version, it would be great.

**Comment by Niemand101** [comment]
Works on 1.6.1.12 will try older versions later.

**Comment by Niemand101** [comment]
Casper, maybe include if (version_compare(_PS_VERSION_, '1.6', '>')) -> $combination, null, null, true
else $combination, true

**Comment by Casper-O** [comment]
That was my thought, but I did like to test out if its necessary before making extra if/else statements. Also as far I understood, the issue happend arround 1.6.1.0 / 1.6.0.14?

I had some issues with my test enviorment doing Easter, so I could not install the older Prestashop Releases to test out the changes

**Comment by Casper-O** [comment]
Hi @Niemand101 did you had the chance to test if https://github.com/dim00z/gshoppingflux/pull/21 worked on lower prestashop version ? Had a few long days since we talked and I won't have time to try for a few more weeks

**Comment by Casper-O** [comment]
I hope the issue is solved - since I have not heard from
