### ISSUE TITLE
Shipping in Feed

### ISSUE THREAD

**Issue by Niemand101** [dim00z/gshoppingflux#22]
For now you can only set fixed shipping in feed. If you have cart / shipping rules with free shipping they don't apply to feed. If you set shipping to 0 (zero) the merchant center settings for shipping do not apply because of given entry.

Solutions:
- calculate shipping based on prestashop rules
- function to disable shipping in feed, but leave <g:shipping></g:shipping> so it can be overrulled by merchant center

**Comment by Casper-O** [comment]
Calculate shipping based on Prestashop shipping tables and Cart Rules could significantly increase time to generate the XML feed.

Leaving the <g:shipping></g:shipping> would most likely be my first solution.

**Comment by Casper-O** [comment]
Try check this commit :)
https://github.com/Casper-O/gshoppingflux/commit/78f44e736cb8b92d01572a630ab65baddee7471a

**Comment by Casper-O** [comment]
Hi I did like to hear your thoughts on #44 if possible.

**Comment by Casper-O** [comment]
#44 solved
