### ISSUE TITLE
Base product on Combinations

### ISSUE THREAD

**Issue by Niemand101** [dim00z/gshoppingflux#23]
When products have combinations, also the base product (which isn't a valid product) is generated in the feed.

Maybe option to add something like: if ($product_combination && is_array($product_combination) else

**Comment by Casper-O** [comment]
Thanks for your issue report.

I saw it after i finished my last PR about Combinations. I'm going to try fix this before i pull the PR over here.

**Comment by Casper-O** [comment]
could you check https://github.com/dim00z/gshoppingflux/pull/21 - I made some changes that should prevent base product from been exported, when combinations is there

**Comment by Casper-O** [comment]
Fixed
