### ISSUE TITLE
When product has no attribute id in title

### ISSUE THREAD

**Issue by Niemand101** [dim00z/gshoppingflux#25]
When a product has no attribute like color, it puts attribute id nr in title.

example:
Ipod Nano Pink = product with color attribute = correct

Ipod Shuffle 3 = product without color attribute (3) = incorrect

needs something to be changed here.

 // Product name
        $title_crop = $product['name'];

        //  Product color attribute, if any
        if (!empty($product['color'])) {
            $title_crop .= ' '.$product['color'];
        }
        if (!empty($product['material'])) {
            $title_crop .= ' '.$product['material'];
        }
        if (!empty($product['pattern'])) {
            $title_crop .= ' '.$product['pattern'];
        }
        if (!empty($product['size'])) {
            $title_crop .= ' '.$product['size'];
        }

        if (Tools::strlen($product['name']) > $title_limit) {
            $title_crop = Tools::substr($title_crop, 0, ($title_limit - 1));
            $title_crop = Tools::substr($title_crop, 0, strrpos($title_crop, ' '));
        }

**Comment by Casper-O** [comment]
Could you make a PR for this change?

**Comment by Casper-O** [comment]
I think i found the reason, could you please confirm this don't happen if you go to https://github.com/dim00z/gshoppingflux/blob/master/gshoppingflux/gshoppingflux.php#L2109 and after this line adds the following:
```
                $product['color'] = '';
                $product['material'] = '';
                $product['pattern'] = '';
                $product['size'] = '';
```
so it says:

```
                $combinum = 0;
                $product['color'] = '';
                $product['material'] = '';
                $product['pattern'] = '';
                $product['size'] = '';
                foreach ($attr as $id_attr => $v) {
```

**Comment by Niemand101** [comment]
no sorry, not working.

 $combinum = 0;
				$product['color'] = '';
                $product['material'] = '';
                $product['pattern'] = '';
                $product['size'] = '';
                foreach ($attr as $id_attr => $v) {
                    foreach ($v as $k => $a) {
                        foreach ($this->categories_values[$product['id_gcategory']]['gcat_color[]'] as $c) {
                            if ($k == $c) {
                                $product['color'] = $a['attribute_name'];

looks like maybe something here: 
https://github.com/dim00z/gshoppingflux/blob/master/gshoppingflux/gshoppingflux.php#L2137

  if (empty($product['color']) && empty($product['material']) && empty($product['pattern']) && empty($product['size'])) {
                        continue 2;
                    }

**Comment by Casper-O** [comment]
Looking at your example - do the iPod shuffle have any combinations at all? Or is it a plain product?

**Comment by Niemand101** [comment]
Casper,

see my live feed here:
https://bot.nl/googleshopping-s1-nl-EUR.xml

look voor product : Varier Variable Balans 3  ( nr 7 from top )

the 3 in the title is from attribute id color. This product is not
available in other color, but other products from same category are.

2017-05-02 11:58 GMT+02:00 Casper Olsen <notifications@github.com>:

**Comment by Casper-O** [comment]
Okay, thanks for the real-life example :)

As far i can see, **Varier Variable Balans** do not have any kind of combinations. Correct?

**Comment by Casper-O** [comment]
Can you check this PR - i have tested it with the following
Product with 3 Attributes
product with only 2 of the Attributes
Product with no Attributes

**Comment by Niemand101** [comment]
Casper,

@3b52f8c is working for me on prestashop 1.6.1.13
