### ISSUE TITLE
Missing recommended attribute: image link

### ISSUE THREAD

**Issue by Niemand101** [dim00z/gshoppingflux#27]
When a product has combinations the <g:image_link> is left blank and only <g:additional_image_link> are filled. There is no cover image on combination, so first image of combination must be <g:image_link> and more images must be <g:additional_image_link>

location [https://github.com/dim00z/gshoppingflux/blob/master/gshoppingflux/gshoppingflux.php#L2267](url)
 foreach ($images as $im) {
            $image = $this->context->link->getImageLink($product['link_rewrite'], $product['id_product'].'-'.$im['id_image'], $image_type);
            $image = preg_replace('*http://'.Tools::getHttpHost().'/*', $this->uri, $image);
            if ($im['cover'] == 1) {
                $xml_googleshopping .= '<g:image_link><![CDATA['.$image.']]></g:image_link>'."\n";
            } else {
                $xml_googleshopping .= '<g:additional_image_link><![CDATA['.$image.']]></g:additional_image_link>'."\n";
            }
            // max images by product
            if (++$nbimages == 10) {
                break;
            }
        }

i wonder if we can strip the   if ($im['cover'] == 1) and replace so first image is <g:image_link> and followinf images are <g:additional_image_link>

**Comment by Casper-O** [comment]
Well sometimes, you might want not the first image to be the cover image. But again I have to say, i don't see why you won't wan't it this way.

**Comment by Casper-O** [comment]
My suggestion would be the following:

if the list of images, don't have one with cover value set to 1, it takes the first image as the one to insert into image_link

https://github.com/dim00z/gshoppingflux/blob/master/gshoppingflux/gshoppingflux.php#L2267-L2279

```
$cover_key = array_search('1', array_column($images, 'cover'));
        foreach ($images as $im_key => $im) {
            $image = $this->context->link->getImageLink($product['link_rewrite'], $product['id_product'].'-'.$im['id_image'], $image_type);
            $image = preg_replace('*http://'.Tools::getHttpHost().'/*', $this->uri, $image);
            if ($im['cover'] == 1 || ($cover_key === false && $im_key == 0)) {
                $xml_googleshopping .= '<g:image_link><![CDATA['.$image.']]></g:image_link>'."\n";
            } else {
                $xml_googleshopping .= '<g:additional_image_link><![CDATA['.$image.']]></g:additional_image_link>'."\n";
            }
            // max images by product
            if (++$nbimages == 10) {
                break;
            }
        }
```

**Comment by g-r-s** [comment]
@Niemand101 Did you manage to get a fix on this? I haven't been able to get the code functioning?
