### ISSUE TITLE
Forum request: No shipping cost pr product

### ISSUE THREAD

**Issue by Casper-O** [dim00z/gshoppingflux#30]
I need to deactivate the shipping costs. How can I do it?
 
I do not want the shipping cost column sent in the feed.
 
The reason is that the module does not let me configure the shipping costs for products over 100 € for example, from that amount my products have free shipping.
 
If I put 0 to the shipping costs, I export the column with that value. Google Merchant Center always chooses the information that is in the feed first, if the information in the feed is not present, then it would pick up the shipping costs that we have set up on your panel.

https://www.prestashop.com/forums/topic/381026-free-module-google-shopping-flux/page-25#entry2565472

**Comment by Dar-us-Salam** [comment]
Yes, this feature will be very much appreciated.
Shoppers from Google are expecting free shipping when they see the listing.

**Comment by Casper-O** [comment]
Should acurally already be working

https://github.com/dim00z/gshoppingflux/pull/33

**Comment by Dar-us-Salam** [comment]
Yes, thanks for the prompt response. Working great. Excellent module!
Just had to select NO for "Use fixed shipping for all products?" so that Google would calculate the rates itself according to the weight.
