### ISSUE TITLE
Only one translation can be enabled

### ISSUE THREAD

**Issue by danielgiljara** [dim00z/gshoppingflux#31]
I'm not able to enable this extension for exporting the feed in different languages.

In the admin area, I go to "Export languages and currencies" section, where all languages and currencies are shown. Then I click "Edit" on a disabled language. In the next screen I have not possibility of enable the language, only click Update. Currency is selected. When I click Update this language continues disabled.

**Comment by Casper-O** [comment]
hi @danielgiljara is the language deactivated for customers in FO ?

I just checked with a multilang site and for now it only allow activated languages to be exported
