### ISSUE TITLE
Handling Product Option Images

### ISSUE THREAD

**Issue by g-r-s** [dim00z/gshoppingflux#34]
It seems to be struggling to handle products with options.

With Clothing for example you just need to send the option i.e. Small/Black. If this individual product does not have an image assigned it will not pick the image from the master product leaving it blank. It would make sense to pass the product image through if there is none for the option.

It will also add a random Attribute to these master products i.e. [Camo Shorts] becomes [Camo Shorts 1 2] as there is no Size/colour option for this product.

Anyone else having this issue or have a viable workaround or code fix?

**Comment by Casper-O** [comment]
So you have the most recent version of the module? That should solve the issue with Randi. Attributes.

Regarding the images, i don't remember if it should fallback to master product yet or if still on todo

**Comment by g-r-s** [comment]
I have downloaded the updated files from here and uploaded them via ftp but it is missing all of the images on the export when i use that? I am using version 1.6.1.6 could it be something to do with that?

Thanks for the reply, really appreciate it.

**Comment by Casper-O** [comment]
1.6.1.x should be fine...

#28 should have fixed the image issue, but i might be mistanken. Sadly i lack time at the moment to look into it

**Comment by g-r-s** [comment]
Hi Yes i have downloaded the latest version here... https://github.com/dim00z/gshoppingflux/releases/tag/v1.6.6

That seems to have done the trick. The only other thing you need to do is under Products > Combinations > Image (this needs to be selected for all options. This fills up the table product_attribute_image which is what the code must be looking for, otherwise it will not output the image.

Thanks great module!

**Comment by Casper-O** [comment]
Might look info fallback if No image for a combination it fallback to "all images".

Dont know if it would make sense

**Comment by g-r-s** [comment]
It is difficult as really it is good practice to assign images if you have products with image variants as google are very picky with the data quality. 

It would make sense if you listed items that just had size variants.
i.e. clothing black t-shirt with variants S, M, L, XL it would work nicely to fallback on all images. 

However you might be selling a size variant item that is different i.e. 330ml, 500ml that have a different image and price.

So it would work, i guess you could specify inconsistencies by each option, then the overall would work.

**Comment by Casper-O** [comment]
I agree with you, but I also need to keep the module simple, but still being powerful...

But in case you just gave it would make sense to assign different images for the size of the bottle (and they you should) while just a size of a black t-shirt you won't...

It's added to my (quite long) todo

**Comment by Casper-O** [comment]
https://github.com/dim00z/gshoppingflux/commit/f2edd17abc1a27c3a8ec0fa2069c6c21e70e5707

this should fix it
