### ISSUE TITLE
Export attributes combinations

### ISSUE THREAD

**Issue by centoasa** [dim00z/gshoppingflux#36]
I've a product with 3 different color attribute.
If the flag is on YES, module don't export the product with attribute; if the flag is NO, export one link for product and export 3 link for 3 different images. Instead maybe (as module says) 3 different link for the 3 different attributes and the 3 link for images

**Comment by sdsoldi** [comment]
Same issue here. If the combination flag is ON, is not exporting products.

**Comment by GuillaumeG22** [comment]
I have the same issue. I will suggest a pull request.

**Comment by Casper-O** [comment]
Thanks for the pull request - it will take some time before I have time to look at it, but it looks promising when I review it on my phone

**Comment by Casper-O** [comment]
@centoasa  let me understand correct.

you have a product, with 1 attribute, that can be 3 different colors? Or do you have 3 attributes, that can each be a color ?

It should work, if you select the attributes as "Products color attribute" in the setup of the category where the product is. Then the feed also tells google that these product have different colors
