### ISSUE TITLE
262 products exported versus only 80 in file

### ISSUE THREAD

**Issue by rakam70** [dim00z/gshoppingflux#38]
Hi,
after export module says:
https://www.......com/googleshopping-s1-it.xml : 262 products exported.
but when I open file only 80 entries inside.
Why?

Thanks a lot in advance.

**Comment by Casper-O** [comment]
Sounds like a bug... is your products with combinations/attributes?

**Comment by rakam70** [comment]
Some have and some no. But it seems that this is not the problem beacuse some in the 80 products exported there are both.

**Comment by Casper-O** [comment]
Could you provide a screenshot of Tour configuartion? Did like to see.. also is you udkig the most recent version? What PrestaShop version is you at?

**Comment by rakam70** [comment]
Solved.
We have quantity management deactivated. So probably some items have qualtity = 0 but we didn't see.
We set "Export non-available products" to "Yes" and the problem is solved.
Sorry and thank you very much for quick answer.

**Comment by Casper-O** [comment]
No harm done... I'm working on a "explain why not exported" thing but I don't have much time to this project :(
