### ISSUE TITLE
Allow to set manually the filename of XML file

### ISSUE THREAD

**Issue by NetVicious** [dim00z/gshoppingflux#45]
Hi!
I know it's easy to change in the source code, but I would like to set manually the filename of the XML on the config page, because the XML file it's public (I know I can set it a htpasswd file, ...) and it should be only downloaded by Google Bots.

**Comment by Casper-O** [comment]
@NetVicious would a prefix be a solution? Something like this:

<your_secret_string>_googleshopping-s1-sv-SEK.xml

**Comment by Casper-O** [comment]
Please check https://github.com/dim00z/gshoppingflux/commit/68e78d7eae5c5f3d24c18c4f9f93f3ed51fd15c3

**Comment by NetVicious** [comment]
Yes, of course that should be enought to get the xml a bit hidden to everyone. Thx.
