### ISSUE TITLE
Inacurate rounding in products with discount

### ISSUE THREAD

**Issue by NetVicious** [dim00z/gshoppingflux#46]
HI! I'm receiving warnings from Google Merchant about different prices of products with discount on web and in the XML Feed.

The price on prestashop differs one or two cents from the XML.

One example can be:
Price of article on web: 19.95€
Discount: 35%
Final price on web: 12.97€ (real should be 12.9675 but rounds up).

Price on XML: <g:price>19.95 EUR</g:price>

Obviously there should be something wrong on the discount calculations on the module.

Regards,

**Comment by Casper-O** [comment]
First of all, thanks for the bug report.

I found what could cause the problem. The module do not use the prestashop rounding methods, and that can cause the issue:
https://github.com/dim00z/gshoppingflux/blob/master/gshoppingflux/gshoppingflux.php#L2363-L2364

To solve it we need to **replace number_format** with **Tools::ps_round($price, $c_decimals)** to match how prestashop calculate the prices.

**Comment by NetVicious** [comment]
Hi Casper-O, thanks for answering.
So we need to change:
```
        $product['price'] = number_format(round($product['price'], 2, PHP_ROUND_HALF_DOWN), 2, '.', ' ');
        $product['price_without_reduct'] = number_format(round($product['price_without_reduct'], 2, PHP_ROUND_HALF_DOWN), 2, '.', ' ');
```

To

```
        $product['price'] = Tools::ps_round(round($product['price'], 2, PHP_ROUND_HALF_DOWN), 2, '.', ' ');
        $product['price_without_reduct'] = Tools::ps_round(round($product['price_without_reduct'], 2, PHP_ROUND_HALF_DOWN), 2, '.', ' ');
```
Or we should remove the round() function inside the price?

**Comment by Casper-O** [comment]
No problem, i'll let the issue report be open so we can solve it in the next release, when the new shipping feature is done

**Comment by Casper-O** [comment]
acually, you should replace **2** with **_PS_PRICE_COMPUTE_PRECISION_** - that way, its not hardcoded and if you for some reason want to have 3 or 4 digits on your prices, it also affects in the module
