### ISSUE TITLE
Why the module doesn't export the correct condition?

### ISSUE THREAD

**Issue by Joslk** [dim00z/gshoppingflux#48]
Hi and thanks for your work,

The module works fine for me but it alwais export the condition of products as "new" not the condition of every product.

How can I fix it?

Thanks.
--
Josele

**Comment by Casper-O** [comment]
Try change the condition for the root category to "Standard", don't know if that would fix it maybe.

**Comment by Joslk** [comment]
Thanks you,

But in that case the module doesn't export the condition of any product and
google refused all the listing.

Best regards.
--
Josele

--
José Luis Hernández Agustín
 TRESMACACOS.com

  C/⁠ Regalado, 12 - Esquina y entrada por Fray Luis de León
  47002 Valladolid
 Telf.: 983 007 264 / 983 10 58 02



Este mensaje y sus archivos adjuntos van dirigidos exclusivamente a su
destinatario, pudiendo contener información confidencial sometida a secreto
profesional. No está permitida su reproducción o distribución sin la
autorización expresa de Música y literatura, S.L.U. Si usted no es el
destinatario final por favor elimínelo e infórmenos por esta vía.

De acuerdo con lo establecido por la Ley Orgánica 15/1999, de 13 de
diciembre, de Protección de Datos de Carácter Personal (LOPD), le
informamos que sus datos están incorporados en un fichero del que es
titular Música y literatura, S.L.U. con la finalidad de realizar la gestión
administrativa, contable y fiscal, así como enviarle comunicaciones
comerciales sobre nuestros productos y/o servicios.

Asimismo, le informamos de la posibilidad de ejercer los derechos de
acceso, rectificación, cancelación y oposición de sus datos de carácter
personal, solicitándolo por escrito en el domicilio de Música y literatura,
S.L.U. sito en la calle Gabilondo, 28, 47007, Valladolid o bien a través de
la dirección de correo electrónico info@tresmacacos.com


2018-02-01 21:42 GMT+01:00 Casper Olsen <notifications@github.com>:

**Comment by Casper-O** [comment]
Okay, and you are running latest version of the module?

What PrestaShop verdion are you using?

**Comment by Casper-O** [comment]
https://github.com/dim00z/gshoppingflux/blob/master/gshoppingflux/gshoppingflux.php#L2143

change to this:
`$sql = 'SELECT DISTINCT p.*, pl.*, ps.id_category_default as category_default, gc.export, glc.tax_included, gl.* '`

It should also still work when you have size/color - tested with default products in 1.6.1.17

**Comment by Joslk** [comment]
Thanks,

I'll check it.

Im using module version 167, because you said that 170 is still on development, and PS 1.6.1.4

**Comment by Casper-O** [comment]
170 should be safe - it just introduced so many new things related to shipment, that i was not sure if it would work right away.

I'll most likely fix this in the next release when i have time for it.

So far i have not heard anything negative related to the new shipping cost option
