### ISSUE TITLE
Add product attribute to feed!

### ISSUE THREAD

**Issue by kmorgen** [dim00z/gshoppingflux#49]
Would it be possible to add these to the feed?:

id_product
id_attribute
id_product-id_attribute 

(it is the ID number for each product)

This ID number is also used by the Facebook Pixel for product ads, so this way the same feed can also be used for Facebook etc.

**Comment by Casper-O** [comment]
Hmmm
Where should this be added for it to be working with facebook etc?
<g:id> ?

**Comment by dominictayloruk** [comment]
yes this should ideally be <g:id>

**Comment by Casper-O** [comment]
Product without combination
`<:gid>id_product-id_product_attribute</g:id>`

Product with combination
`<:gid>id_product</g:id>`

That is what we are looking for, right ? I have been thinking about this for a long time and think your right about this

**Comment by dim00z** [comment]
Hi, 

It seems you're right... do you plan to build a new version? 

dim 


----- Mail original -----

De: "Casper Olsen" <notifications@github.com> 
À: "dim00z/gshoppingflux" <gshoppingflux@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Mardi 16 Octobre 2018 10:06:29 
Objet: Re: [dim00z/gshoppingflux] Add product attribute to feed! (#49) 



Product without combination 
<:gid>id_product-id_product_attribute</g:id> 

Product with combination 
<:gid>id_product</g:id> 

That is what we are looking for, right ? I have been thinking about this for a long time and think your right about this

**Comment by Casper-O** [comment]
Changed it here and will be part of an upcoming release: https://github.com/dim00z/gshoppingflux/commit/35f0b2ea412952c0497092730dd439a6a33116e1
