### ISSUE TITLE
Notice: $shop_id not found in gshoppingflux.php line 2051

### ISSUE THREAD

**Issue by davidglezz** [dim00z/gshoppingflux#59]
function [_getOutputFileName](https://github.com/dim00z/gshoppingflux/blob/master/gshoppingflux/gshoppingflux.php#L2051) has 2 variables not found: `$shop_group_id` and `$shop_id`.

**Comment by zendalmig** [comment]
Hello:

Use instead $this->context->shop->id_shop_group, $this->context->shop->id

Code like this:

if (Configuration::get('GS_FILE_PREFIX', '', $this->context->shop->id_shop_group, $this->context->shop->id)) {
            return Configuration::get('GS_FILE_PREFIX', '', $this->context->shop->id_shop_group, $this->context->shop->id).'_googleshopping-s'.$shop.'-'.$lang.'-'.$curr.'.xml';
        }

**Comment by Casper-O** [comment]
https://github.com/dim00z/gshoppingflux/commit/2cfb1f698654bc2664ac3ef1d3d9d754812dfe2f
