### ISSUE TITLE
Fatal error: Allowed memory size

### ISSUE THREAD

**Issue by vasco-info** [dim00z/gshoppingflux#60]
i have this error then i tried to install the module on my test website : 
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 98304 bytes) in /modules/gshoppingflux/gcategories.class.php on line 178
[PrestaShop] Fatal error in module file : modules/gshoppingflux/gcategories.class.php:
Allowed memory size of 268435456 bytes exhausted (tried to allocate 98304 bytes)

any idea ??

**Comment by Casper-O** [comment]
Your server is running out of memory - is it doing that when the module is installed?

How many categories and languages do you have ?
