### ISSUE TITLE
Not all the links to images exported to xml feed file

### ISSUE THREAD

**Issue by Pavel060907** [dim00z/gshoppingflux#62]
Good day!

I faced the issue that there are just 19 exported products of 1660 has a container with a link to image of a product. So the google merchant center is not accepting the most of the list. I don't see the difference in these products and don't understand why it happens. Could you help to resolve the issue.

**Comment by Casper-O** [comment]
Sorry, can you try to explain a little more in detail what the problem is? i don't understand it.

**Comment by Casper-O** [comment]
Closed, no response
