### ISSUE TITLE
Can't edit "Google categories" in 1.7.4.3

### ISSUE THREAD

**Issue by PrestaShark** [dim00z/gshoppingflux#65]
Hi. Can not change or map a category in in 1.7.4.3.
Thanks with support on this! Where donation can be send? :)

**Comment by Casper-O** [comment]
Hi could you be a bit more specific with your issue, maybe even add a screenshot of how the module configuration is looking regarding the categories?

Regarding donation, im not really sure about. I do have some Crypto wallets like BTC/ETH - alternative I maybe have an old paypal account
