### ISSUE TITLE
Prestashop 1.7.4.4. This file is not a module in a valid ZIP format.

### ISSUE THREAD

**Issue by kont69** [dim00z/gshoppingflux#67]
Hi,
I can't upload this file. Error: "This file is not a module in a valid ZIP format." in my prestashop 1.7.4.4.
thanks.
Marc

**Comment by Casper-O** [comment]
What file?

Did you download one of the release?

**Comment by kont69** [comment]
Hi,
I download this file. I can’t upload.
Marc

________________________________
De: Casper Olsen <notifications@github.com>
Enviado: Friday, November 9, 2018 12:32:33 PM
Para: dim00z/gshoppingflux
Cc: kont69; Author
Asunto: Re: [dim00z/gshoppingflux] Prestashop 1.7.4.4. This file is not a module in a valid ZIP format. (#67)


What file?

Did you download one of the release?

**Comment by Casper-O** [comment]
Download latest version, at the release page you find here...

https://github.com/dim00z/gshoppingflux/releases

https://github.com/dim00z/gshoppingflux/releases/download/v1.7.1/gshoppingflux-1.7.1.zip

**Comment by kont69** [comment]
Hi,
I upload the latest module.
Thanks.
Marc



________________________________
De: Casper Olsen <notifications@github.com>
Enviado: Saturday, November 10, 2018 8:55:26 PM
Para: dim00z/gshoppingflux
Cc: kont69; Author
Asunto: Re: [dim00z/gshoppingflux] Prestashop 1.7.4.4. This file is not a module in a valid ZIP format. (#67)


Download latest version, at the release page you find here...

https://github.com/dim00z/gshoppingflux/releases

https://github.com/dim00z/gshoppingflux/releases/download/v1.7.1/gshoppingflux-1.7.1.zip
