### ISSUE TITLE
It doesn't export discounted Prices.

### ISSUE THREAD

**Issue by ndrpssdnt** [dim00z/gshoppingflux#68]
Why it doesn't export discounted prices?

**Comment by Casper-O** [comment]
Hi Please come with a little more information.

It sure do export discounted price, in stores im currently using it on... fx:

**Comment by Casper-O** [comment]
Hi Please come with a little more information. module version, store version etc...

It sure do export discounted price, in stores im currently using it on... fx:

```
<g:price>4499 DKK</g:price>
<g:sale_price>3899 DKK</g:sale_price>
```

**Comment by ndrpssdnt** [comment]
I didn't check the file, it works, sorry. :+1:
