### ISSUE TITLE
403 error on cron.php

### ISSUE THREAD

**Issue by pinkypandapup** [dim00z/gshoppingflux#73]
I've installed the module successfully and it's working great. The only problem I am having is I'm receiving a 403 error when I try to access the cron.php file, so I am having to manual update the feed constantly myself.

Any advice?

**Comment by Casper-O** [comment]
Hi

403 FORBIDDEN
The server understood the request but refuses to authorize it.

It is hard to say what could be the reason, but try check the chmod is ok for cron.php

**Comment by pinkypandapup** [comment]
Appears to have been a permissions issue as it's working now, thank you.
