### ISSUE TITLE
virustotal alert VEX.Webshell

### ISSUE THREAD

**Issue by rss9090** [dim00z/gshoppingflux#85]
https://github.com/dim00z/gshoppingflux/releases/download/v1.7.3/gshoppingflux-1.7.3.zip

casuses alert VEX.Webshell on Virustotal BKAV antivirus

**Comment by Casper-O** [comment]
Bkav is a very aggressive scanner and shows a lot of false positives, that is also the case with this plug-in.

For example, google "bkav vex.webshell" or "vex.webshell false positive", and you'll see the numerous reports of it being a false positive.
