### ISSUE TITLE
Shipping cost calculation don't match quickcost chronopost module option

### ISSUE THREAD

**Issue by Noubeuh** [dim00z/gshoppingflux#91]
Hi, 
I am using Prestashop 1.7.2.4 with the google shopping flux module 1.7.0. I know it's not the last version but i don't think this is related, ping me if i'm wrong.

We use the chronopost module with the quickcost option which calculate new shipping cost basing on carrier shipping configuration + client's negociation with the carrier.

Because of that, the shipping cost can't match the market shipping cost in the feed. I'm still working on it but if someone has already encounter this issue (which i didn't see here) let me know.

Thank you for reading.

**Comment by Casper-O** [comment]
To check external shipping costs like in this, the module would need to use the `getOrderShippingCost() `function in the chronopost module, but it would also require that each single product was put in a cart before check, the module worked like this once but used up massive amount of carts evey time the feed is generat to check each product, and it also used a lot of ressources.

https://github.com/dim00z/gshoppingflux/blob/master/gshoppingflux/gshoppingflux.php#L2622-L2634

**Comment by Noubeuh** [comment]
Thank you for your answer.

Overriding the module by adding getOrderShippingCost() worked for me.
