### ISSUE TITLE
No error but only 2 products exported

### ISSUE THREAD

**Issue by grzegorzgit** [dim00z/gshoppingflux#93]
I have about 40 products with combinations, together it is about 200 products.  I get this "success" message:
![image](https://user-images.githubusercontent.com/24461669/99411336-c6a81400-28f3-11eb-88c6-333d29515628.png)

Why 187 products are not exported? No information what to check or change or what is the reason for not exporting them.
Also, what exactly means "**2 products exported: 10 products with attributes, 15 attributes combinations**"? This message makes no sense.

**Comment by Casper-O** [comment]
Could you provide a image of your configuration? That would help to identify the issue.

**Comment by Casper-O** [comment]
no more info given
